export const GET_WELCOME_INITIATE = 'GET_WELCOME_INITIATE';
export const GET_WELCOME_SUCCESS = 'GET_WELCOME_SUCCESS';
export const CHAGE_USER_ID = 'CHAGE_USER_ID';
export const GET_WELCOME_FINISH = 'GET_WELCOME_FINISH';
